### ISSUE TITLE
accounts: implement basic model and roles

### ISSUE THREAD

**Issue by BrunoRosendo** [NIAEFEUP/website-niaefeup-backend-old#3]
This issue is meant to have an investigation part where you need to discover the best way of implementing accounts with roles and permissions in Spring Boot, this is a very common need in APIs so I'm sure the framework will have something to help us here.

After that, you should implement an account model with basic functionalities and the necessary roles. You can take a look at [the accounts of the current website](https://github.com/NIAEFEUP/Website-NIAEFEUP/blob/develop/src/models/User.js). The point is just for inspiration and not to recreate their model, we can have something different that fits our needs here.

## Tasks
- [x] Create an Account model
- [x] Create basic Account endpoints
- [x] Create models for Roles and Permissions
- [x] Integrate the Roles with the Account model

**Comment by DoStini** [comment]
add role of project manager to manage people in their projects

**Comment by limwa** [comment]
Here's what we came up with today:

![IMG_20220927_164144__01.jpg](https://user-images.githubusercontent.com/13498603/192621461-93c68822-a023-47d2-b1d3-c63edd3392d5.jpg)
![IMG_20220927_174458__01.jpg](https://user-images.githubusercontent.com/13498603/192622087-d138f6b1-289c-46d3-a833-9476d7468c9c.jpg)

**Comment by BrunoRosendo** [comment]
This issue turned out fairly big so I'll split it into different tasks
